[package]
name = "decode-tx-example"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-primitives = { path = "../..", features = ["bincode-serialize"] }
base64 = "0.22.0"
borsh = "0.10.3"
bs58 = "0.5.0"
hex = "0.4.3"
bincode = "1.3.3"
