[package]
name = "decode-tx-example"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-primitives = { path = "../../solana-primitives", features = [
    "bincode-serialize",
] }
base64.workspace = true
borsh.workspace = true
bs58.workspace = true
hex.workspace = true
