[package]
name = "decode-tx-example"
version.workspace = true
edition.workspace = true

[dependencies]
solana-primitives = { path = "../../solana-primitives" }
base64.workspace = true
borsh.workspace = true
bs58.workspace = true
hex.workspace = true
