[package]
name = "basic-example"
version.workspace = true
edition.workspace = true

[dependencies]
borsh.workspace = true
solana-primitives = { path = "../../solana-primitives", features = ["jsonrpc"] }
tokio.workspace = true
