[package]
name = "basic-example"
version.workspace = true
edition.workspace = true

[dependencies]
borsh.workspace = true
base64.workspace = true
bs58.workspace = true
hex.workspace = true
solana-primitives = { path = "../../solana-primitives" }
