[package]
name = "basic-example"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-primitives = { path = "../..", features = ["jsonrpc"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "time"] }
borsh = "0.10.4"
