[package]
name = "basic-example"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh.workspace = true
solana-primitives = { path = "../../solana-primitives", features = ["jsonrpc"] }
tokio.workspace = true
